## Quantitative proteomics

##      | Label-free | Labelled    |
## -----+------------+-------------|
## MS1  | XIC        | SILAC, 15N  |
## MS2  | Counting   | TMT (iTRAQ) |

## https://lazear.github.io/sage/
## https://uclouvain-cbio.github.io/sager/

library(tidyverse)
library(msdata)
library(QFeatures)

## Quantitative assay -> SummarizedExperiment
##
## - quantitative data: matrix [features x samples]
## - samples/columns annotation (meta-data)
## - features/rows annotation (meta-data)

## - quantitative data: assay()
## - samples/columns annotation: colData()
## - features/rows annotation: rowData()

## Multiple SummarizedExperiment (PSM, peptides, proteins, ...) are
## combined into a QFeatures object.

data(feat1)
feat1

se <- feat1[[1]]
feat1[["psms"]]

se
assay(se)
rowData(se)
colData(se)

colData(feat1)

colData(feat1)$X <- c("X1", "X2")
feat1$Y <- c("Y1", "Y2")

colData(feat1)

assay(feat1)

feat1
rowData(feat1[[1]])

feat1 <- aggregateFeatures(
    feat1,
    i = "psms",
    fcol = "Sequence",
    name = "peptides",
    fun = colMeans
)

feat1

assay(feat1[[1]])
assay(feat1[[2]])

rowData(feat1[[2]])


feat1 <- aggregateFeatures(
    feat1,
    i = "peptides",
    fcol = "Protein",
    name = "proteins",
    fun = colMeans
)

feat1


feat1["ProtA", , ]

filterFeatures(feat1, ~ pval < 0.05)

filterFeatures(feat1, ~ pval < 0.05, keep = TRUE)

## As an exercise, filter rows of proteins that localise to the
## mitochondrion.

filterFeatures(feat1, ~ location == "Mitochondrion")

## Creating QFeatures objects

## data generated by PD
data(hlpsms)

hl <- readQFeatures(hlpsms,
                    ecol = 1:10,
                    name = "psms")

hl

colData(hl)

colData(hl)$group <- rep(c("CTRL", "COND"),
                         each = 5)
assay(hl[[1]])
rowData(hl[[1]])


se <- readSummarizedExperiment(hlpsms,
                               ecol = 1:10)
se

colData(se)

QFeatures(list(psms = se))

## CPTAC

## tab-delimited file generated by MQ
basename(f <- msdata::quant(full.names = TRUE))


## Read these data in as either a SummarizedExperiment (or a
## QFeatures) object.

read.delim(f) |>
    DT::datatable()


i <- 56:61
i <- grep("Intensity\\.", names(read.delim(f)))

cptac_se <- readSummarizedExperiment(f,
                                     ecol = i,
                                     fname = "Sequence",
                                     sep = "\t")

colData(cptac_se)

colnames(cptac_se) <- sub("I.+\\.", "", colnames(cptac_se))

colnames(cptac_se)

colData(cptac_se)$condition <- rep(c("6A", "6B"), each = 3)
colData(cptac_se)$id <- rep(7:9, 2)

names(rowData(cptac_se))

## --> contaminant database/fasta: CRAP

keep_vars <- c("Sequence", "Proteins", "Leading.razor.protein",
               "PEP", "Score", "Reverse", "Potential.contaminant")

rowData(cptac_se) <- rowData(cptac_se)[, keep_vars]

## Pipeline
